networks:
  dev:

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - dev
    
  frontend:
    build: ./test_app
    networks:
      - dev