import { Open_Sans, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/header";


const openSans = Open_Sans({
  variable: "--font-open_sans",
  subsets: ["latin"],
});

const montserratSans = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${montserratSans.variable} antialiased bg-white`}
      >
        <Header></Header>
        
        {children}
      </body>
    </html>
  );
}
