import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Navigation from "./components/navigation";


const openSans = Open_Sans({
  variable: "--font-open_sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} antialiased bg-white`}
      >
        <Header></Header>
        <main className="relatieve w-full flex h-screen pt-12">
          <Navigation />
        </main>
        {children}
      </body>
    </html>
  );
}
